import React from "react";
import { getAllTeamMembers } from "../../../../sanity/lib/queries";
import { safeUrlFor, type SanityImage } from "@/lib/sanity-image";

type TeamMember = {
  name: string;
  role: string;
  bio: string;
  years: string;
  image?: string;
};

type SanityTeamMember = {
  _id: string;
  name: string;
  role: string;
  bio?: string;
  years?: string;
  image?: SanityImage;
};

// Sample headshot served from /public/team — used until real photos are
// uploaded in Sanity. These are AI-generated placeholders (no real person).
// Generated by scripts/seed-team-images.mjs.
const sampleAvatar = (name: string) =>
  `/team/${name.trim().replace(/\s+/g, "-").toLowerCase()}.jpg`;

// Fallback data — used when Sanity has no team members configured yet.
const fallbackTeam: TeamMember[] = [
  {
    name: "Anthony Keever",
    role: "Chief Executive Officer",
    bio: "Established Diamond Edge Cutting in Ireland in 1997 and relocated the company to the UAE in 2008. Under his leadership, DEC has grown year on year to become one of the leading and best-known names in GCC demolition, with an exceptional clients list, an enviable track record and a highly skilled workforce.",
    years: "30+ years · concrete cutting, drilling, demolition",
    image: sampleAvatar("Anthony Keever"),
  },
  {
    name: "Robert Aylward",
    role: "Managing Director",
    bio: "Drives day-to-day leadership across operations, projects, and client relationships. Robert brings deep specialist demolition expertise across Ireland, Europe, and the GCC, with hands-on programme delivery on the region's most technically challenging jobs.",
    years: "25+ years · demolition & project delivery",
    image: sampleAvatar("Robert Aylward"),
  },
  {
    name: "Conor Wade",
    role: "Operations Manager",
    bio: "Oversees DEC's operational delivery on every active site, from method statements and HSE plans to plant deployment and crew scheduling. Conor ensures every project runs on programme, on safety, and within the approved scope.",
    years: "20+ years · site operations & HSE",
    image: sampleAvatar("Conor Wade"),
  },
  {
    name: "Carl Riley",
    role: "Commercial Manager",
    bio: "Leads DEC's commercial function, contracts, cost control, and strategic pricing across tenders, variations, and final account. Carl combines value engineering with rigorous commercial discipline to protect margin and deliver outcomes that work for clients and DEC alike.",
    years: "18+ years · construction commercial",
    image: sampleAvatar("Carl Riley"),
  },
  {
    name: "Jithesh Vannadil",
    role: "Estimation Manager",
    bio: "Leads DEC's estimation function, translating tender documents and site conditions into accurate, competitive bids. Jithesh brings disciplined quantification and cost modelling across demolition and specialist cutting packages.",
    years: "15+ years · estimation & cost planning",
    image: sampleAvatar("Jithesh Vannadil"),
  },
  {
    name: "Laxmikant Prajapat",
    role: "Finance Manager",
    bio: "Manages the company's financial operations, reporting, and statutory compliance across UAE entities. Laxmikant brings disciplined cash management, audit readiness, and finance partnering to project teams across the business.",
    years: "15+ years · finance & compliance",
    image: sampleAvatar("Laxmikant Prajapat"),
  },
];

function initialsOf(name: string) {
  return name
    .split(" ")
    .map((p) => p[0])
    .join("")
    .slice(0, 2);
}

function Avatar({ member, className }: { member: TeamMember; className?: string }) {
  return (
    <div
      className={`relative rounded-full overflow-hidden bg-brand-red/10 flex items-center justify-center shrink-0 ${className ?? "w-16 h-16"}`}
    >
      {member.image ? (
        // eslint-disable-next-line @next/next/no-img-element
        <img
          src={member.image}
          alt={member.name}
          className="absolute inset-0 w-full h-full object-cover"
        />
      ) : (
        <span className="font-display font-bold uppercase text-brand-red text-[22px] tracking-tight leading-none">
          {initialsOf(member.name)}
        </span>
      )}
    </div>
  );
}

export async function Leadership() {
  let team: TeamMember[] = fallbackTeam;

  try {
    const sanityTeam = (await getAllTeamMembers()) as SanityTeamMember[];
    if (sanityTeam && sanityTeam.length > 0) {
      team = sanityTeam.map((m) => ({
        name: m.name,
        role: m.role,
        bio: m.bio ?? "",
        years: m.years ?? "",
        image: safeUrlFor(m.image, 800) ?? undefined,
      }));
    }
  } catch (error) {
    const msg = error instanceof Error ? error.message : String(error);
    console.warn(`[Sanity] team fetch failed (${msg.slice(0, 120)}); using local fallback.`);
  }

  // Anthony (CEO) and Robert (MD) lead the section; the rest sit in a static
  // grid below.
  const featured = team.slice(0, 2);
  const rest = team.slice(2);

  return (
    <section className="py-16 md:py-24 bg-white">
      <div className="container mx-auto px-4 md:px-8">
        {/* Heading + featured leadership */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-10 lg:gap-12 mb-12 md:mb-16">
          <div className="lg:col-span-5 flex items-start lg:items-center">
            <h2 className="font-display font-extrabold uppercase text-brand-gray-900 text-[44px] md:text-[72px] lg:text-[88px] leading-[0.92] tracking-tight [&_em]:font-light [&_em]:italic [&_em]:text-brand-red [&_em]:normal-case">
              Meet the <em>team.</em>
            </h2>
          </div>
          <div className="lg:col-span-7 grid grid-cols-1 sm:grid-cols-2 gap-5 md:gap-6">
            {featured.map((member) => (
              <article
                key={member.name}
                className="bg-brand-gray-100 border-t-2 border-brand-red p-7 md:p-8 flex flex-col gap-4"
              >
                <div className="flex items-center gap-4">
                  <Avatar member={member} />
                  <div className="flex flex-col gap-1">
                    <h3 className="font-display font-bold uppercase text-brand-gray-900 text-[18px] md:text-[20px] tracking-[0.06em] leading-[1.05]">
                      {member.name}
                    </h3>
                    <p className="font-mono text-[10px] md:text-[10.5px] uppercase tracking-[0.16em] text-brand-red">
                      {member.role}
                    </p>
                  </div>
                </div>
                {member.bio && (
                  <p className="font-['Inter_Display',sans-serif] text-[13.5px] md:text-[14px] leading-[1.6] text-brand-gray-600">
                    {member.bio}
                  </p>
                )}
              </article>
            ))}
          </div>
        </div>

        {/* Rest of the team — static grid, no scroll animation */}
        <div className="grid grid-cols-2 lg:grid-cols-4 gap-4 md:gap-5">
          {rest.map((member) => (
            <article
              key={member.name}
              className="bg-brand-gray-100 border-t-2 border-brand-red p-6 flex flex-col gap-4 group"
            >
              <Avatar member={member} />
              <div className="flex flex-col gap-1">
                <h3 className="font-display font-bold uppercase text-brand-gray-900 text-[16px] md:text-[18px] tracking-[0.06em] leading-[1.05]">
                  {member.name}
                </h3>
                <p className="font-mono text-[10px] md:text-[10.5px] uppercase tracking-[0.16em] text-brand-red">
                  {member.role}
                </p>
              </div>
            </article>
          ))}
        </div>
      </div>
    </section>
  );
}
